import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  vus: 50,
  duration: '1m',
  thresholds: {
    http_req_duration: ['p(95)<300'],
    http_req_failed: ['rate<0.01'],
  },
};

const BASE_URL = 'http://localhost:8000/api/v1';

export default function () {
  const loginRes = http.post(`${BASE_URL}/auth/login`, JSON.stringify({
    username: 'carlos',
    password: 'demo123',
  }), {
    headers: { 'Content-Type': 'application/json' },
  });

  check(loginRes, {
    'logged in successfully': (r) => r.status === 200 || r.status === 201,
  });

  sleep(1);

  const listRes = http.get(`${BASE_URL}/requests?status=OPEN&page=1&limit=20`);
  check(listRes, {
    'list fetched successfully': (r) => r.status === 200,
  });

  sleep(1);

  const dashboardRes = http.get(`${BASE_URL}/dashboard/summary`);
  check(dashboardRes, {
    'dashboard fetched successfully': (r) => r.status === 200,
  });

  sleep(1);

  const createRes = http.post(`${BASE_URL}/requests`, JSON.stringify({
    title: 'Load Test Request',
    description: 'Generated by k6 load test',
  }), {
    headers: { 'Content-Type': 'application/json' },
  });

  check(createRes, {
    'request created successfully': (r) => r.status === 201,
  });

  sleep(1);
}
