import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  vus: 50,
  duration: '1m',
  thresholds: {
    http_req_duration: ['p(95)<300'],
    http_req_failed: ['rate<0.01'],
  },
};

const BASE_URL = 'http://localhost:8000/api/v1';

export default function () {
  const loginRes = http.post(`${BASE_URL}/auth/login`, JSON.stringify({
    username: 'carlos',
    password: 'demo123',
  }), {
    headers: { 'Content-Type': 'application/json' },
  });

  check(loginRes, {
    'logged in successfully': (r) => r.status === 200 || r.status === 201,
  });

  const cookies = loginRes.cookies;
  const cookieHeader = Object.keys(cookies)
    .map((name) => `${name}=${cookies[name][0].value}`)
    .join('; ');

  const authHeaders = {
    'Content-Type': 'application/json',
    Cookie: cookieHeader,
  };

  sleep(1);

  const listRes = http.get(`${BASE_URL}/requests?status=OPEN&page=1&limit=20`, {
    headers: authHeaders,
  });
  check(listRes, {
    'list fetched successfully': (r) => r.status === 200,
  });

  sleep(1);

  const dashboardRes = http.get(`${BASE_URL}/dashboard/summary`, {
    headers: authHeaders,
  });
  check(dashboardRes, {
    'dashboard fetched successfully': (r) => r.status === 200,
  });

  sleep(1);

  const createRes = http.post(`${BASE_URL}/requests`, JSON.stringify({
    title: `Load Test ${__VU}-${__ITER}-${Date.now()}`,
    description: 'Generated by k6 load test',
    category: 'TI',
  }), {
    headers: authHeaders,
  });

  check(createRes, {
    'request created successfully': (r) => r.status === 201,
  });

  sleep(1);
}